version: '3.8'

networks:
    frontend:
        name: frontend
    storage:
        name: storage
    email:
        name: email

volumes:
    gravitee-data-elasticsearch:
    gravitee-data-mongo:
    apim-mongodb-logs:
    apim-gateway-logs:
    apim-management-api-logs:
    apim-management-ui-logs:
    apim-portal-ui-logs:

services:
    mongodb:
        image: mongo:${MONGODB_VERSION:-6.0}
        container_name: gio_apim_mongodb
        restart: always
        volumes:
            - gravitee-data-mongo:/data/db
            - apim-mongodb-logs:/var/log/mongodb
        healthcheck:
            test: mongosh --eval 'db.runCommand({serverStatus:1}).ok' --quiet | grep 1
            interval: 5s
            timeout: 3s
            retries: 10
        networks:
            - storage

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-8.17.2}
        container_name: gio_apim_elasticsearch
        restart: always
        volumes:
            - gravitee-data-elasticsearch:/usr/share/elasticsearch/data
        environment:
            - http.host=0.0.0.0
            - transport.host=0.0.0.0
            - xpack.security.enabled=false
            - cluster.name=elasticsearch
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile: 65536
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s']
            interval: 5s
            timeout: 3s
            retries: 10
        networks:
            - storage

    gateway:
        image: ${APIM_REGISTRY:-graviteeio}/apim-gateway:${APIM_VERSION:-latest}
        container_name: gio_apim_gateway
        restart: always
        depends_on:
            mongodb:
                condition: service_healthy
            elasticsearch:
                condition: service_healthy
        volumes:
            - apim-gateway-logs:/opt/graviteeio-gateway/logs
            - ./.license:/opt/graviteeio-gateway/license
        environment:
            - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
            - gravitee_ratelimit_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
            - gravitee_reporters_elasticsearch_endpoints_0=http://elasticsearch:9200
            - 'license.key=${LICENSE_KEY}'
        networks:
            - storage
            - frontend

    management_api:
        image: ${APIM_REGISTRY:-graviteeio}/apim-management-api:${APIM_VERSION:-latest}
        container_name: gio_apim_management_api
        restart: always
        links:
            - mongodb
            - elasticsearch
        depends_on:
            mongodb:
                condition: service_healthy
            elasticsearch:
                condition: service_healthy
        volumes:
            - apim-management-api-logs:/opt/graviteeio-management-api/logs
            - ./.license:/opt/graviteeio-management-api/license
        environment:
            - gravitee_management_mongodb_uri=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
            - gravitee_analytics_elasticsearch_endpoints_0=http://elasticsearch:9200
            - gravitee_email_enabled=true
            - gravitee_email_host=mailhog
            - gravitee_email_port=1025
            - gravitee_email_subject="TEST"
            - gravitee_email_from="user@my.domain"
            - 'license.key=${LICENSE_KEY}'
        networks:
            - storage
            - frontend
            - email

    management_ui:
        image: ${APIM_REGISTRY:-graviteeio}/apim-management-ui:${APIM_VERSION:-latest}
        container_name: gio_apim_management_ui
        restart: always
        depends_on:
            - management_api
        environment:
            - MGMT_API_URL=${MGMT_API_URL}
            #- DEFAULT_PORTAL=next # Uncomment to set the portal-next as the default portal for management UI environment redirection.
        volumes:
            - apim-management-ui-logs:/var/log/nginx
        networks:
            - frontend

    portal_ui:
        image: ${APIM_REGISTRY:-graviteeio}/apim-portal-ui:${APIM_VERSION:-latest}
        container_name: gio_apim_portal_ui
        restart: always
        depends_on:
            - management_api
        environment:
            - PORTAL_API_URL=${PORTAL_API_URL}
            #- DEFAULT_PORTAL=next # Uncomment to set the portal-next as default portal
        volumes:
            - apim-portal-ui-logs:/var/log/nginx
        networks:
            - frontend

    mailhog:
        image: mailhog/mailhog
        container_name: gio_apim_mailhog
        restart: always
        #ports:
        #    - '8025:8025'
        #    - '1025:1025'
        networks:
            - email
